export const Roles = {
  SUPERUSER: "SUPERUSER",
  SALES: "SALES",
  PURCHASING: "PURCHASING",
  WAREHOUSE: "WAREHOUSE",
  FINANCE: "FINANCE",
  MANAGER_SALES: "MANAGER_SALES",
  MANAGER_PURCHASING: "MANAGER_PURCHASING",
  MANAGER_FINANCE: "MANAGER_FINANCE",
  MANAGER_WAREHOUSE: "MANAGER_WAREHOUSE",
} as const;
